-- Seed Data for BatTechno Appointments
-- Run this after creating the schema

-- Insert Admin User (password: Admin123!)
-- Password hash is bcrypt hash of "Admin123!"
-- You need to generate this using bcrypt in your application
-- For now, this is a placeholder - you should insert the actual hash from your seed script

-- Note: You need to run the backend seed script to properly hash the password
-- This SQL is just for reference structure

-- Example Admin User (password hash needs to be generated by bcrypt)
-- INSERT INTO users (id, full_name, email, password_hash, role, language, is_active, is_email_verified)
-- VALUES (
--     uuid_generate_v4(),
--     'Admin User',
--     'admin@battechno.com',
--     '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyY5Y5Y5Y5Y5', -- Replace with actual bcrypt hash
--     'ADMIN',
--     'ar',
--     true,
--     true
-- );

-- Sample FAQs
INSERT INTO faqs (question_ar, answer_ar, question_en, answer_en, "order", is_active) VALUES
(
    'كيف يمكنني حجز موعد؟',
    'يمكنك حجز موعد من خلال صفحة حجز المواعيد. اختر نوع الموعد (حضوري أو عن بعد)، ثم اختر التاريخ والوقت المناسبين.',
    'How can I book an appointment?',
    'You can book an appointment through the booking page. Choose the appointment type (in-person or online), then select a suitable date and time.',
    1,
    true
),
(
    'ما هي أوقات العمل؟',
    'أوقات العمل من الساعة 9 صباحاً حتى 5 مساءً، من الأحد إلى الخميس.',
    'What are the working hours?',
    'Working hours are from 9 AM to 5 PM, Sunday to Thursday.',
    2,
    true
),
(
    'كيف يمكنني إلغاء موعد؟',
    'يمكنك إلغاء موعد من خلال صفحة مواعيدي. اختر الموعد المراد إلغاؤه واضغط على زر الإلغاء.',
    'How can I cancel an appointment?',
    'You can cancel an appointment through the My Appointments page. Select the appointment you want to cancel and click the cancel button.',
    3,
    true
);

